version: '3.4'

services:
  resume:
    image: stevenresume
    build:
      context: data
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
